---
# Variables for configureing the AMI build instance

epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"

root_directory: /srv/private
ntptimeservers:
  - 0.nz.pool.ntp.org
  - 1.nz.pool.ntp.org
  - 2.nz.pool.ntp.org
  - 3.nz.pool.ntp.org

docker:
  volumes:
    - apache_config
    - apache_data

ami_build_instance_id:
